#!/bin/bash

PATH=$(cd $(dirname $0); pwd):$PATH

rep=""

if  ! estrepertoire $1
then
    exit 1
fi


for i in $(ls $1)
do
   
    if estrepertoire $1/$i
       
    then
        
	rep=$rep:$i
    fi

done
echo $rep

    


   

   
