#!/bin/bash

PATH=$(cd $(dirname $0); pwd):$PATH


i=1

echo nom de la commande "       "  \$0  =  $0
echo
echo nombre d arguments "       "  \$#  =  $#
echo
echo
echo


while ! estpareil $# 0
do
	echo argument numero $i "      "   '$'$i =  $1
	i=$(expr $i + 1)
	shift

done
