#!/bin/bash


echo DEBUG
indice=1

echo nom de la commande "       "  \$0  =  $0
    
echo nombre d arguments "       "  \$#  =  $#
    

for i in $*
do   
    echo argument numero $indice "      "   '$'$i =  $i
    indice=$(expr $indice + 1 )
done






